---
- name: Ensure Git is installed
  become: true
  ansible.builtin.package:
    name: git
    state: present

- name: Ensure target directory exists
  ansible.builtin.file:
    path: "{{ base16_shell_target_dir }}"
    state: directory
    mode: "u=rwx,g=rx,o="

- name: Ensure base16-shell repo is available
  ansible.builtin.git:
    repo: "https://github.com/chriskempson/base16-shell.git"
    version: master
    dest: "{{ base16_shell_repo_dir }}"

- name: Ensure selected theme is set
  ansible.builtin.file:
    src: "{{ base16_shell_repo_dir }}/scripts/base16-{{ base16_shell_theme }}.sh"
    dest: "{{ ansible_user_dir }}/.base16_theme"
    state: link
    mode: "u=rw,g=,o="
