---
- name: Ensure yubikey-touch-detector is installed
  become: true
  package:
    name: yubikey-touch-detector
    state: present

- name: Ensure configuration directory exists
  file:
    path: "{{ yubikey_touch_detector_config_dir }}"
    state: directory
    mode: "u=rwx,g=,o="

- name: Ensure configuration is present
  template:
    src: service.conf.j2
    dest: "{{ yubikey_touch_detector_config_dir }}/service.conf"
    mode: "u=r,g=,o="

- name: Ensure service is enabled and started
  ansible.builtin.systemd:
    name: yubikey-touch-detector
    enabled: true
    state: started
    scope: user
