---
namespace: dannixon
name: user

version: 0.0.9

readme: readme.md

authors:
  - Dan Nixon <dan@dan-nixon.com>

description: A collection of user level configuration and service roles.

license: MIT

repository: https://github.com/DanNixon/ansible-user
issues: https://github.com/DanNixon/ansible-user/issues
