---
galaxy_info:
  author: dannixon
  description: Creates dircolors configuration file
  license: MIT
  min_ansible_version: 2.1
  platforms:
    - name: ArchLinux
    - name: Ubuntu

dependencies: []
