---
driver:
  name: podman

platforms:
  - name: archlinux
    image: archlinux
    pre_build_image: false

lint: |
  set -ex
  ansible-lint

provisioner:
  name: ansible

verifier:
  name: testinfra
