---
name: Role Testing

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 2,16 * *"

jobs:
  molecule:
    name: Molecule
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        role:
          - base16_shell
          - dircolors
          - nerdfont
          - pass
          - yubikey_touch_detector
        scenario:
          - default

    steps:
      - uses: dannixon/ansible-testing/actions/test_role@main
        with:
          role: "${{ matrix.role }}"
          scenario: "${{ matrix.scenario }}"
